
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development_slave_database:
  adapter: sqlite3
  database: db/development_slave.sqlite3
  pool: 5
  timeout: 5000


# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
test_slave_database:
  adapter: sqlite3
  database: db/test_slave.sqlite3
  pool: 5
  timeout: 5000

