
development:
  adapter: sqlite3
  database: test/db/development.sqlite3
  pool: 5
  timeout: 5000

development_slave_database:
  adapter: sqlite3
  database: test/db/development_slave.sqlite3
  pool: 5
  timeout: 5000

